# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_symptoms', models.CharField(max_length=5000)),
                ('disease_probability', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material_url', models.URLField(default='http://google.com', max_length=300)),
                ('material_image_url', models.URLField(default='http://google.com', max_length=300)),
                ('material_rating', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_disease', models.CharField(max_length=100)),
            ],
        ),
    ]
